"""subscriptions payments price_rules

Phase 2A. Money is Numeric(12,2), never float. payments.order_reference is UNIQUE —
that constraint is what makes a repeated Approved extend access exactly once.

Revision ID: 3b37e7b502b1
Revises: 490198f772df
Create Date: 2026-09-30 18:20:53.645788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b37e7b502b1'
down_revision: Union[str, Sequence[str], None] = '490198f772df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('resolved_user_id', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_price_rules_username')
    )
    op.create_index(op.f('ix_price_rules_username'), 'price_rules', ['username'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'past_due', 'expired', 'cancelled', name='subscriptionstatus', native_enum=False, length=24), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_tier', sa.Enum('custom', 'community', 'regular', name='pricetier', native_enum=False, length=24), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reminder_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('free_period_granted', sa.Boolean(), nullable=False),
    sa.Column('wayforpay_rec_token', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('order_reference', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'pending', 'complete', 'denied', 'canceled', 'refunded', 'refunded_partial', 'reversed', 'error', name='paymentstatus', native_enum=False, length=24), nullable=False),
    sa.Column('invoice_url', sa.String(length=512), nullable=True),
    sa.Column('wayforpay_status', sa.String(length=32), nullable=True),
    sa.Column('reason_code', sa.String(length=16), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_reference'), 'payments', ['order_reference'], unique=True)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_reference'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_price_rules_username'), table_name='price_rules')
    op.drop_table('price_rules')
    # ### end Alembic commands ###
