"""discounts replace price rules

Phase 2A. `price_rules` held one absolute price per username with no expiry. `discounts`
supports a percentage or a fixed price, an optional `valid_until`, `granted_by` for audit, and
soft revocation so past invoices stay explainable.

The downgrade uses generic SQLAlchemy types (String/Numeric/DateTime), not the uppercase
VARCHAR/NUMERIC/DATETIME that autogenerate produced. Those were reflected from a SQLite
database and are SQLite spellings: PostgreSQL has no DATETIME type, so the downgrade failed
in CI with 'type "datetime" does not exist'. Anything hand-checked on SQLite needs reading
for dialect-specific types before it is trusted on Postgres.

Also renames the `subscriptions.price_tier` value `custom` to `discounted`. Autogenerate cannot
see that: the column is a plain VARCHAR (native_enum=False, no CHECK), so nothing in the schema
records the allowed values. Left undone, an old row would fail validation on load.

Revision ID: 42440559cfe0
Revises: 3b37e7b502b1
Create Date: 2026-09-30 22:03:23.132527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42440559cfe0'
down_revision: Union[str, Sequence[str], None] = '3b37e7b502b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('kind', sa.Enum('percent', 'fixed_price', name='discountkind', native_enum=False, length=24), nullable=False),
    sa.Column('percent_off', sa.Integer(), nullable=True),
    sa.Column('fixed_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discounts_live', 'discounts', ['revoked_at', 'valid_until'], unique=False)
    op.create_index(op.f('ix_discounts_user_id'), 'discounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_discounts_username'), 'discounts', ['username'], unique=False)
    op.drop_index(op.f('ix_price_rules_username'), table_name='price_rules')
    op.drop_table('price_rules')
    # PriceTier.CUSTOM was renamed to DISCOUNTED.
    op.execute("UPDATE subscriptions SET price_tier = 'discounted' WHERE price_tier = 'custom'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('resolved_user_id', sa.BigInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name=op.f('uq_price_rules_username'))
    )
    op.create_index(op.f('ix_price_rules_username'), 'price_rules', ['username'], unique=False)
    op.drop_index(op.f('ix_discounts_username'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_user_id'), table_name='discounts')
    op.drop_index('ix_discounts_live', table_name='discounts')
    op.execute("UPDATE subscriptions SET price_tier = 'custom' WHERE price_tier = 'discounted'")
    op.drop_table('discounts')
    # ### end Alembic commands ###
