"""discount free first period

Adds the flag that lets a listed member receive a free first period without being detectable
as a channel member — a bot cannot enumerate a channel's membership, so most existing members
have to be listed by hand.

server_default is required, not cosmetic: adding a NOT NULL column to a table that already has
rows fails without one, and discounts may well be populated by the time this runs.

Revision ID: eb3fa5ab8ba6
Revises: 42440559cfe0
Create Date: 2026-10-01 21:23:15.673674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3fa5ab8ba6'
down_revision: Union[str, Sequence[str], None] = '42440559cfe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'discounts',
        sa.Column(
            'free_first_period',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discounts', 'free_first_period')
    # ### end Alembic commands ###
